"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
from xml.etree.ElementInclude import include

from setuptools import setup

APP = ['YtdlpDownloader.py']
DATA_FILES = []
OPTIONS = {
    'includes': ["PyQt5", "yt_dlp"]
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
